version: "3.9"
services:
  ### FastAPI server
  server:
    image: ghcr.io/uptrain-ai/uptrain:latest
    restart: always
    entrypoint: ["python", "app.py"]
    working_dir: "/app/"
    volumes:
      - "$SERVER_DATA_DIR:/data/"
    env_file:
      - .env
    ports:
      - 4300:4300
    profiles: ["server"]

  ###  dashboard
  dashboard:
    image: ghcr.io/uptrain-ai/uptrain-dashboard:latest
    restart: always
    entrypoint: ["npm", "run", "dev"]
    working_dir: "/app/"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    ports:
      - 3000:3000
    profiles: ["server"]

networks:
  default:
    name: uptrain-network
