prompts: [prompts.txt]
providers: [openai:chat:gpt-3.5-turbo-0613, openai:chat:gpt-4]
tests:
  - description: 'UpTrain Test'
    vars:
      question: Which is the most popular global sport?
      context: The popularity of sports can be measured in various ways, including TV viewership, social media presence, number of participants, and economic impact. Football is undoubtedly the world's most popular sport with major events like the FIFA World Cup and sports personalities like Ronaldo and Messi, drawing a followership of more than 4 billion people. Cricket is particularly popular in countries like India, Pakistan, Australia, and England. The ICC Cricket World Cup and Indian Premier League (IPL) have substantial viewership. The NBA has made basketball popular worldwide, especially in countries like the USA, Canada, China, and the Philippines. Major tennis tournaments like Wimbledon, the US Open, French Open, and Australian Open have large global audiences. Players like Roger Federer, Serena Williams, and Rafael Nadal have boosted the sport's popularity. Field Hockey is very popular in countries like India, Netherlands, and Australia. It has a considerable following in many parts of the world.
    assert:
      - type: python
        value: |
            # import subprocess
            # import sys
            from loguru import logger
            # a = subprocess.check_call([sys.executable, "-m", "pip", "install","-q", "uptrain==0.5.0"])
            import uptrain.framework
            import json
            data = [{
              'question': 'Which is the most popular global sport?',
              'context': "The popularity of sports can be measured in various ways, including TV viewership, social media presence, number of participants, and economic impact. Football is undoubtedly the world's most popular sport with major events like the FIFA World Cup and sports personalities like Ronaldo and Messi, drawing a followership of more than 4 billion people. Cricket is particularly popular in countries like India, Pakistan, Australia, and England. The ICC Cricket World Cup and Indian Premier League (IPL) have substantial viewership. The NBA has made basketball popular worldwide, especially in countries like the USA, Canada, China, and the Philippines. Major tennis tournaments like Wimbledon, the US Open, French Open, and Australian Open have large global audiences. Players like Roger Federer, Serena Williams, and Rafael Nadal have boosted the sport's popularity. Field Hockey is very popular in countries like India, Netherlands, and Australia. It has a considerable following in many parts of the world.",
              'response': output
            }]
            logger.remove()
            eval_llm = uptrain.framework.EvalLLM(openai_api_key="sk-****************")
            results = eval_llm.evaluate(
              data=data,
              checks=[uptrain.framework.Evals.FACTUAL_ACCURACY]
            )
            # sys.stdout = old_stdout
            if results[0]['score_factual_accuracy']>0.5:
              print(json.dumps({
                  'pass': True,
                  'score': results[0]['score_factual_accuracy'],
                  'reason': results[0]['explanation_factual_accuracy'],
                }))
            else:
              print(json.dumps({
                  'pass': False,
                  'score': results[0]['score_factual_accuracy'],
                  'reason': results[0]['explanation_factual_accuracy'],
                }))
