name: Translate README

on:
  push:
    branches: [*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Use the personal access token to authenticate with GitHub
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Russian
        uses: dephraiim/translate-readme@main
        with:
          LANG: ru
